### ISSUE TITLE
add instructions to the repo, so we can add color/texture to the instructions

### ISSUE THREAD

**Issue by nilesjohnson** [timhutton/klein-quartic#1]
For example:

https://github.com/nilesjohnson/klein-quartic/commit/552ac387946530447a971fa00414a547fc09f9ae

**Comment by timhutton** [comment]
Hi Niles,

Yes. If you have a color printer it would be good to choose a more mathematically interesting tiling too, like an 8-coloring where no two colors touch. If you look in the python code some of these colorings are listed, it would be a useful option to a) produce the PDF automatically, and b) fill with the desired color or texture.

**Comment by nilesjohnson** [comment]
ah; I wish I had thought to do that!

**Comment by timhutton** [comment]
The new version outputs SVG (which can be converted to PDF using e.g. Inkscape). There's an option to output SVG with filled-in colors.
