### ISSUE TITLE
Clarify instructions

### ISSUE THREAD

**Issue by nilesjohnson** [timhutton/klein-quartic#2]
I was confused at a couple of points in the instructions.  Here are some things that were difficult:
- Numbers on the colored heptagonal tiling of H^2 are hard to read.
- If you extend the numbering out of the fundamental domain, it will help clarify the instructions.
- Each piece has 2 edges with the same label.  This makes instructions such as 12B - 13B ambiguous -- which B tab to use?
- The instruction 3B - 11B appears twice!  Probably one of them should be 3B - 17B.
- Maybe indicate with line style which direction to crease internal edges in each heptagon -- this can be seen from the 3D model, but its tough.
- Surely the big step can be formatted a little nicer!  I got lost several times ;)

**Comment by nilesjohnson** [comment]
According my model, here's how the numbering extends -- maybe this will clarify 3B

![1451436331685869887510](https://cloud.githubusercontent.com/assets/3353209/12044730/c412ead0-ae64-11e5-95f0-47fbd8a2ef86.jpg)

**Comment by timhutton** [comment]
Hi Niles, Many thanks for your help with this. I've fixed most of these issues with #4.
